export const API_BASE_URL = 'http://192.168.2.69:3000';
export const LOGIN_ENDPOINT = '/login-register/login';
export const USERS_ENDPOINT = '/users';
export const USERS_ROLES = '/roles';
export const UPDATE_USERS='/users/updateAll'
export const REGISTER_USERS='/login-register/register'
export const ROLE_PERMISSSIONS='/roles-permission'
export const PERMISSIONS='/permissions'
export const CHARGE='/charge'
export const DEPARTMENT='/department'
export const AREA_CHARGE='/area-charge'
export const PROJECTS='/projects'
export const MATERIAL='/material'
export const ASIGNATURE_PROJECTS='/area-charge-projects'
export const AREA_CHARGE_PROJECTS='/projects-material'